server:
  port: 5000

app:
  cors:
    allowed-origin: ${FRONTEND_URL:http://localhost:3000}
  cookie:
    secure: false
    same-site: Lax

jwt:
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
